name: Linux Release
permissions:
  contents: write

on:
  push:
    tags:
      - '*'
      - '!*-alpha*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Build Backend (amd64)
        run: |
          go mod download
          go build -ldflags "-s -w ' -extldflags '-static'" -o ip-pool-proxy

      - name: Release Binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
           ip-pool-proxy
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
